apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejspgloadtest-deploy
  labels:
    app: nodejspgloadtest
spec:
  selector:
    matchLabels:
      app: nodejspgloadtest
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodejspgloadtest
    spec:
      containers:
        - name: nodejspgloadtest
          image: nikolasmelui/nodejspgloadtest:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
