apiVersion: v1
kind: Service
metadata:
  name: nodejspgloadtest-service
  labels:
    app: nodejspgloadtest
spec:
  type: ClusterIP
  selector:
    app: nodejspgloadtest
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
